#!/bin/bash

case "$1" in

  install)
    pip install -r "./requirements.txt"
    ;;

  test)
    # Run Test Cases
    echo "Test Cases"
    ;;

  *)
    # Run with URL_FILE
    echo "URL_FILE"
    ;;

esac

